# Generated by Django 3.2.11 on 2022-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_num', models.CharField(max_length=15)),
                ('owner', models.CharField(max_length=50)),
                ('mob_num', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
