# Generated by Django 4.0.2 on 2022-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('mail', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'owners',
            },
        ),
        migrations.CreateModel(
            name='Vehicle_owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=15)),
                ('owner_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vehicle_owners',
            },
        ),
        migrations.DeleteModel(
            name='LP',
        ),
    ]
